# Generated by Django 4.1.3 on 2024-07-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, max_length=1, upload_to='')),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('U', 'UNISEX')], default='M', max_length=1)),
                ('descricao_longa', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('C', 'PAGO'), ('A', 'A PAGAR')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
