# Generated by Django 4.1.3 on 2024-08-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do tipo')),
                ('descricao_curta', models.CharField(max_length=50, verbose_name='Descrição simples')),
            ],
            options={
                'verbose_name': 'Tipo de produto',
                'verbose_name_plural': 'Tipos de produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da venda')),
                ('status', models.CharField(choices=[('C', 'PAGO'), ('A', 'A PAGAR')], default='C', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='loja.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('volume', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Imagem do produto')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor do produto')),
                ('modelo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('U', 'UNISEX')], default='M', max_length=1, verbose_name='Modelo')),
                ('descricao_curta', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição simples')),
                ('descricao_longa', models.TextField(verbose_name='Descrição longa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.tipoproduto', verbose_name='Tipo do produto')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='loja.produto', verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(verbose_name='Data de solicitação')),
                ('data_prevista_entrega', models.DateField(verbose_name='Data prevista de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente', verbose_name='Cliente')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.venda', verbose_name='Pedido')),
            ],
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(check=models.Q(('volume__gte', 1)), name='quantidade do produto'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gte', 1)), name='quantidade_gte_1'),
        ),
    ]
