# Generated by Django 4.1.3 on 2024-07-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
