# Generated by Django 4.1.3 on 2024-08-06 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_tipoproduto_categoriaproduto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
