# Generated by Django 4.1.3 on 2024-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('C', 'ABERTO'), ('A', 'FECHADO')], default='C', max_length=1, verbose_name='Status'),
        ),
    ]
