# Generated by Django 4.1.3 on 2024-08-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_categoriaproduto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProduto',
            new_name='Categoria',
        ),
    ]
