# Generated by Django 4.1.3 on 2024-08-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_cliente_pedido_nome_alter_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nome',
            new_name='cliente',
        ),
    ]
