# Generated by Django 4.1.3 on 2024-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_categoriaproduto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da categoria'),
        ),
    ]
