# Generated by Django 4.1.3 on 2024-07-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tipo_consulta', models.CharField(choices=[('E', 'Exame'), ('C', 'Consulta'), ('V', 'Vacina')], default='C', max_length=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.veterinario')),
            ],
        ),
    ]
