# Generated by Django 4.1.3 on 2024-07-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='deleted_at',
        ),
    ]
